package com.udemySpringCourse.app.ws.io.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.udemySpringCourse.app.ws.shared.dto.UserDto;

import javax.persistence.*;
import java.io.Serializable;

@Entity(name="addresses") //name is the name of the database table
public class AddressEntity implements Serializable {

    @Id
    @GeneratedValue //autogenerated
    private long id;

    @Column(length=30, nullable=false) //a required field
    private String addressId; //we can share it publically

    @Column(length=15, nullable=false) //a required field
    private String city;

    @Column(length=15, nullable=false) //a required field
    private String country;

    @Column(length=100, nullable=false) //a required field
    private String streetName;

    @Column(length=7, nullable=false) //a required field
    private String postalCode;

    @Column(length=10, nullable=false) //a required field
    private String type;

    @ManyToOne //Many addresses can belong to 1 user
    @JoinColumn(name="users_id") //common field
    @JsonIgnore //cause of ASSERTION FAILED ***: "!errorOutstanding" with message transform method call failed at JPLISAgent.c line: 844
    private UserEntity userDetails;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getAddressId() {
        return addressId;
    }

    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getStreetName() {
        return streetName;
    }

    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public UserEntity getUserDetails() {
        return userDetails;
    }

    public void setUserDetails(UserEntity userDetails) {
        this.userDetails = userDetails;
    }
}


